// <auto-generated />
using System;
using EMaigrator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMaigrator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EmaigratorDbContext))]
    [Migration("20260601215906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.CredentialRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CipherBlob")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SecretRef")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.FolderTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MailboxMigrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MailboxMigrationId");

                    b.ToTable("folder_tasks", (string)null);
                });

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestConnectionRef")
                        .HasColumnType("text");

                    b.Property<string>("DestProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBatch")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceConnectionRef")
                        .HasColumnType("text");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StoreSubjects")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WizardStep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.LedgerEntryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DestFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MailboxMigrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailboxMigrationId", "IdentityKey")
                        .IsUnique();

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.MailboxMigration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestMailbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FailedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<long>("MigratedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceMailbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("mailbox_migrations", (string)null);
                });

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.MigrationLogRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<Guid>("MailboxMigrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MailboxMigrationId");

                    b.ToTable("migration_logs", (string)null);
                });

            modelBuilder.Entity("EMaigrator.Infrastructure.Data.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
